### ISSUE TITLE
Create docker image for neo4j + recommendation engine

### ISSUE THREAD

**Issue by wouterd** [part-up/api#38]
Based on neo4j version 2.
Add graphaware and the UCBF recommendation engine. See https://github.com/part-up/UBCF-algorithm
adjust neo4j.properties so graphaware and the ucbf engine are run.

**Comment by vanderGoes** [comment]
Neo4j 3.0 Enterprise (startup license) + plugins:
- graphaware-server-community-3.0.1.38.10.jar (or a higher version)
- graphaware-reco-3.0.1.38.10.jar (or a higher version)
- ubcf.jar

Settings for Neo4j in conf/neo4jproperties.

`#Enable GraphAware Runtime
com.graphaware.runtime.enabled=true

#Register the Recommendation Module
com.graphaware.module.reco.1=com.graphaware.reco.neo4j.module.RecommendationModuleBootstrapper

#Express for which nodes recommendations should be computed
com.graphaware.module.reco.node=hasLabel('User')

#Define which Recommendation Engine to use
com.graphaware.module.reco.engine=com.partup.ubcf.reco

#Optionally, specify how many recommendation to compute (default is 10)
com.graphaware.module.reco.maxRecommendations=30

#Optionally, specify the Relationship Type of the relationship linking people with their recommended friends (default is RECOMMEND)
com.graphaware.module.reco.relationshipType=RECO_RANDOM`

**Comment by wouterd** [comment]
Fixed in https://github.com/part-up/UBCF-algorithm/issues/1
