### ISSUE TITLE
Implement API endpoint for recommended partups

### ISSUE THREAD

**Issue by wouterd** [part-up/api#39]
URL: /partups/recommended/for/user/{userId}

userId is encrypted with a shared secret (api key) => AES, Base64Encoded.

Output: Partup IDs, sorted by relevance, fex;
```
{
    partUpIds: [“18u2ejdlfas”, “9283urfdsalfjasl”]
}
```

Data comes from a neo4j Cypher query.

**Comment by vanderGoes** [comment]
@AnnotatedJS Zie ook bovenstaand.

**Comment by tlimpanont** [comment]
Are we able to get encrypted userId from the front end? What we can do is 
```
Meteor.userId() // "K5c5M4Pbdg3B82wQH"
```
But this is MongoDB Id I guess.

**Comment by tlimpanont** [comment]
<img width="530" alt="screen shot 2016-07-26 at 14 15 40" src="https://cloud.githubusercontent.com/assets/617876/17137528/e5997bb6-533b-11e6-8da0-e5b28c24f1ad.png">

**Comment by tlimpanont** [comment]
```javascript
var bla = crypto.createCipher('aes-128-ecb', '0123456789012345');

bla.update('adsfasfas'); // <SlowBuffer>

bla.final('utf-8');
```

**Comment by wouterd** [comment]
# For NodeJS

First you need to create the key for aes by MD5ing the api auth key:
```
> var hash = crypto.createHash('md5')
undefined
> hash.update('some-mock-value1')
Hash { _handle: {}, _options: undefined }
> hash.digest('hex')
'85fd90d0aedebe23bff1048c3ca06d07'
```

Then you have to encrypt the upper Id like follows:

```
> var cipher = crypto.createCipheriv('aes-128-ecb', new Buffer('85fd90d0aedebe23bff1048c3ca06d07', 'hex'), new Buffer(0))
undefined
> var encrypted = cipher.update('a7qcp5RHnh5rfaeW9', 'utf-8', 'base64') + cipher.final('base64')
'XrAMse2B5c3o554omlTK+o6HKtFlwlnCn4RXFS3ZbXM='
```

Then turn the resulting string into base64 url encoded as follows:

```
var urlElement = encrypted.replace(/\+/g,'-').replace(/\//g,'_')
```

**Comment by tlimpanont** [comment]
I've changed the code to 

https://github.com/part-up/part-up/commit/266c08511321a03b33f497f2a5f1d314ebc482e7

got  

```
The requested resource could not be found.
```

after visit http://api.ft-recommended-partups-dev.staging.part-up.com/partups/recommended/for/user/kijhyXbNVRYF5QHd+NHcIyqV6tj2R15qoPm/5e95yx8=

**Comment by wouterd** [comment]
I see you have a slash and a plus in your user Id. You need to do the string replacements still. :) It's now base64 encoded, not base64 url encoded.

**Comment by vanderGoes** [comment]
Aaah, damn. 
Which makes kijhyXbNVRYF5QHd-NHcIyqV6tj2R15qoPm_5e95yx8 right?
Now I get `Unable to parse user Id, make sure it's encrypted and base64 encoded.`

**Comment by wouterd** [comment]
Yeah, you were using the wrong passphrase.

**Comment by tlimpanont** [comment]
EVENT_ENDPOINT_AUTHORIZATION is unknown in meteor client right?

**env.sh**
```
export PORT=3000
export TEMP_DIR=/tmp
export CLOUD_DIR=/tmp

export PARTUP_CRON_ENABLED="1"

export FACEBOOK_APP_ID=""
export FACEBOOK_APP_SECRET=""

export LINKEDIN_API_KEY=""
export LINKEDIN_SECRET_KEY=""

export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_BUCKET_REGION=""
export AWS_BUCKET_NAME=""

export FLICKR_API_KEY=""
export FLICKR_SECRET_KEY=""
export FLICKR_GROUP_ID=""

export EVENT_ENDPOINT_URL=""
export EVENT_ENDPOINT_AUTHORIZATION=""
#export LOG_EVENTS=true

export GOOGLE_API_KEY=""

export METEOR_SETTINGS="{\"public\":{\"analyticsSettings\":{\"Google Analytics\":{\"trackingId\":\"\"}}}}"

export PUSH_APPLE_APN_PFX="";
export PUSH_GOOGLE_GCM_API="";

```

**Comment by wouterd** [comment]
It's a server env var, yes.

**Comment by vanderGoes** [comment]
`PARTUP_API_AUTHKEY: mock-auth-value1` in docker-compose.yml? But this is part of the decrypt by Ansible right? Or is this switched?

**Comment by wouterd** [comment]
Yes, they're decrypted by ansible for production. Not so much for local test docker-compose ymls. :)

**Comment by vanderGoes** [comment]
@wouterd Guess this one can be closed right?

**Comment by wouterd** [comment]
Yep!
