### ISSUE TITLE
Terminate UpdateNeo4jActor when the event is processed

### ISSUE THREAD

**Issue by asomov** [part-up/api#5]
EventRoutingActor creates an instance of UpdateNeo4jActor for every Event. When the event is processed the ActorRef stays as a child of EventRoutingActor. 
It looks like a memory leak.
The simplest solution would be to send PoisonPill (http://doc.akka.io/docs/akka/current/scala/actors.html#Actor_Lifecycle)
(We can also use a pool of actors if we need to manage the load for Neo4j. It can be implemented later.)

**Comment by wouterd** [comment]
Fixed
